### ISSUE TITLE
pysqlite2 won't compile on OS X 10.6.6

### ISSUE THREAD

**Issue by ghaering** [ghaering/pysqlite#31]
_From [phil.stp...@gmail.com](https://code.google.com/u/106334239209624537714/) on February 09, 2011 01:25:35_

What steps will reproduce the problem? 1. Alter setup.cfg --> #define=SQLITE_OMIT_LOAD_EXTENSION
2. Run 'python setup.py build' or ... install 3. What is the expected output? What do you see instead? estrella:pysqlite-2.6.1 stephens$ sudo python setup.py buildrunning build
running build_py
running build_ext
building 'pysqlite2._sqlite' extension
gcc-4.0 -fno-strict-aliasing -fno-common -dynamic -isysroot /Developer/SDKs/MacOSX10.4u.sdk -arch ppc -arch i386 -g -O2 -DNDEBUG -g -O3 -DMODULE_NAME="pysqlite2.dbapi2" -I/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6 -c src/module.c -o build/temp.macosx-10.3-fat-2.6/src/module.o
In file included from /Library/Frameworks/Python.framework/Versions/2.6/include/python2.6/unicodeobject.h:4,
                 from /Library/Frameworks/Python.framework/Versions/2.6/include/python2.6/Python.h:85,
                 from src/connection.h:26,
                 from src/module.c:24:
/Developer/SDKs/MacOSX10.4u.sdk/usr/include/stdarg.h:4:25: error: stdarg.h: No such file or directory
In file included from /Library/Frameworks/Python.framework/Versions/2.6/include/python2.6/unicodeobject.h:4,
                 from /Library/Frameworks/Python.framework/Versions/2.6/include/python2.6/Python.h:85,
                 from src/connection.h:26,
                 from src/module.c:24:
/Developer/SDKs/MacOSX10.4u.sdk/usr/include/stdarg.h:4:25: error: stdarg.h: No such file or directory
In file included from src/module.c:27:
src/backup.h:34: error: syntax error before ‘sqlite3_backup’
src/backup.h:34: warning: no semicolon at end of struct or union
src/backup.h:37: error: syntax error before ‘}’ token
src/backup.h:37: warning: data definition has no type or storage class
In file included from src/module.c:27:
src/backup.h:34: error: syntax error before ‘sqlite3_backup’
src/backup.h:34: warning: no semicolon at end of struct or union
src/backup.h:37: error: syntax error before ‘}’ token
src/backup.h:37: warning: data definition has no type or storage class
lipo: can't figure out the architecture type of: /var/tmp//ccLKAEFd.out
error: command 'gcc-4.0' failed with exit status 1
estrella:pysqlite-2.6.1 stephens$ ls What version of the product are you using? On what operating system? 2.6.1 on Darwin 10.6.6 Please provide any additional information below. File it complains about does exist:

estrella:pysqlite-2.6.1 stephens$ ls /Developer/SDKs/MacOSX10.4u.sdk/usr/include/std
stdarg.h   stdbool.h  stddef.h   stdint.h   stdio.h    stdlib.h  
estrella:pysqlite-2.6.1 stephens$ ls /Developer/SDKs/MacOSX10.4u.sdk/usr/include/std

_Original issue: http://code.google.com/p/pysqlite/issues/detail?id=31_
